FROM python:3.10-bookworm

ENV PYTHONUNBUFFERED=1

WORKDIR /django

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

RUN python3 firstrun.py

CMD gunicorn Backend.wsgi:application --bind 0.0.0.0:8000

EXPOSE 8000

